forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/apache'
mod 'puppetlabs/apt','1.8.0'
mod 'puppetlabs/concat','1.2.2'
mod 'puppetlabs/firewall'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/inifile'
mod 'puppetlabs/ntp'
mod 'puppetlabs/pe_gem'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/xinetd'
mod 'adrien/alternatives'
mod 'camptocamp/bind'
mod 'croddy/make'
mod 'elasticsearch/elasticsearch'
mod 'elasticsearch/logstash'
mod 'evenup/redis'
mod 'gentoo/portage'
mod 'huit/ipa'
mod 'ispavailability/file_concat'
mod 'theforeman/concat_native'
mod 'theforeman/dhcp'
mod 'theforeman/dns'
mod 'theforeman/foreman'
mod 'theforeman/foreman_proxy'
mod 'theforeman/puppet'
mod 'theforeman/tftp'
mod 'zack/r10k'

mod 'arthurjames',
  :git => 'https://github.com/mlambrichs/arthurjames-puppetmaster.git'
