forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/catalog_preview'
mod 'puppetlabs/concat'
mod 'puppetlabs/firewall'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/inifile'
mod 'puppetlabs/java'
mod 'puppetlabs/ntp'
mod 'puppetlabs/pe_gem'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'puppet/extlib'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/xinetd'
mod 'adrien/alternatives'
mod 'attachmentgenie/timezone'
mod 'inkblot/bind'
mod 'croddy/make'
mod 'gentoo/portage'
mod 'ispavailability/file_concat'
mod 'puppet/collectd'
mod 'ripienaar/module_data'
mod 'theforeman/concat_native'
mod 'theforeman/dhcp'
mod 'theforeman/dns'
mod 'theforeman/foreman'
mod 'theforeman/foreman_proxy'
mod 'theforeman/puppet'
mod 'theforeman/tftp'
mod 'zack/r10k'

mod 'arthurjames',
  :git => 'https://github.com/mlambrichs/arthurjames-modules.git'
mod 'carbon_c_relay',
  :git => 'https://github.com/mlambrichs/puppet-carbon_c_relay.git'
mod 'neo4j',
  :git => 'https://github.com/mlambrichs/puppet-neo4j.git',
  :branch => 'skyscrapers-neo4j_refactor'
